version: "3.2"      

services:           
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_volume:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  redis:
    image: redis
    command: redis-server --port 6379
    container_name: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

volumes:
  mongo_volume:
  redis_volume: